---
- hosts: mywebserver
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on redhat
    yum:
     nameeee: httpd
     state: present
    notify: starthttpd
    ignore_errors: yes
    when: ansible_os_family=="RedHat"
  - name: start the httpd service
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"
  - name: copy the index file from CM to all redhat nodes
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
    when: ansible_os_family=="RedHat"
  handlers:
  - name: start the httpd service
    service:
     name: starthttpd
     state: started
    when: ansible_os_family=="RedHat" 